### ISSUE TITLE
question for the seq2seq

### ISSUE THREAD

**Issue by WakeUpAmen** [spro/practical-pytorch#13]
In the seq2seq example,  the input sentence is fed into the encoder one word by one word using a for loop:

    for ei in range(input_length):
        encoder_output, encoder_hidden = encoder(input_variable[ei], encoder_hidden)
        encoder_outputs[ei] = encoder_output[0][0]

This is different with other seq2seq examples like this: 
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L141
,where the sentence is fed into the encoder only once.

My question is, I am curious are these two equivalent? Thanks!

**Comment by spro** [comment]
They are mostly equivalent, and I use the for loop version to make it clear for the tutorial. However it is a better idea to use the all-at-once version generally, because it is better optimized on the GPU (and using batching would be even more optimized). I actually have an update coming soon that will include that.

**Comment by WakeUpAmen** [comment]
thanks!
