### ISSUE TITLE
Why using multiple optimizers

### ISSUE THREAD

**Issue by lan2720** [spro/practical-pytorch#34]
Hi, thanks! Your seq2seq-translation tutorial is great!

I notice you're using two optimizers for encoder and decoder module individually.
```
# Initialize optimizers and criterion
encoder_optimizer = optim.Adam(encoder.parameters(), lr=learning_rate)
decoder_optimizer = optim.Adam(decoder.parameters(), lr=learning_rate * decoder_learning_ratio)
```
I'm curious why you do so. Does it mean I should create optimizers as many as the number of sub-modules I've created in the model? 
Since there is usually a single optimizer in Tensorflow seq2seq code, is there any consideration to separate the training process of these two parts?

**Comment by spro** [comment]
The purpose was to make it explicit that the encoder and decoder are two separate modules working together, and secondarily to experiment with different learning rates. There have been a lot of questions about this so I'll probably change it to one module with one optimizer.

Generally you can just combine them like so:

```python
class Seq2Seq(nn.Module):
    def __init__(self, ...):
        super(Seq2Seq, self).__init__()

        self.encoder = Encoder(...)
        self.decoder = Decoder(...)

    def forward(self, inputs):
        encoder_outputs = encoder(...)
        decoder_outputs = decoder(...)
```

Mostly pseudocode but the important part is assigning the sub-modules to `self` of the parent module so that their parameters are registered.
